<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="APT04-GYTN0J3" failures="1" tests="2" name="Error Test" time="22.887" errors="0" timestamp="2024-12-20T19:00:07 IST">
  <testcase classname="stanalone.tests.StandAloneTestWithPageObjectsErrorMessage" name="itemValidation2" time="14.152">
    <failure type="java.lang.AssertionError" message="expected [ZARA COAT 3] but found [IPHONE 13  PRO]">
      <![CDATA[java.lang.AssertionError: expected [ZARA COAT 3] but found [IPHONE 13  PRO]
at stanalone.tests.StandAloneTestWithPageObjectsErrorMessage.itemValidation2(StandAloneTestWithPageObjectsErrorMessage.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- itemValidation2 -->
  <testcase classname="stanalone.tests.StandAloneTestWithPageObjectsErrorMessage" name="loginValidation" time="0.899"/>
  <testcase classname="stanalone.tests.StandAloneTestWithPageObjectsErrorMessage" name="itemValidation1" time="0.0">
    <ignored/>
  </testcase> <!-- itemValidation1 -->
</testsuite> <!-- Error Test -->
